### ISSUE TITLE
Check sounds

### ISSUE THREAD

**Issue by PCelestia** [MineLittlePony/Love-and-Tolerance#35]
some sounds that aren't in the resourcepack:
- [ ] upward travelling bubbles when something is in it

I haven't done much looking around for sounds, I just noticed this one

**Comment by Sollace** [comment]
Unless we're actually _changing_ the game's sounds, we shouldn't have any in the pack. Default sounds are all distributed and updated separately from the base game.

**Comment by PCelestia** [comment]
I know, I just wanted to have a list of things that we might want to add. 
Also, after doing some investigation, what I thought was from the resourcepack was vanilla. so nevermind
